-- Deploy pong:init to pg

BEGIN;

CREATE TABLE game (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE player (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE score (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    game_id INT NOT NULL REFERENCES game(id),
    player_id INT NOT NULL REFERENCES player(id),
    points INT NOT NULL CHECK(points >= 0)
);

COMMIT;
